stages:
  - prepare
  - deploy

before_staging:
  stage: prepare
  tags:
    - staging
  only:
    - develop
  script:
    - cd /applications/nextline/staging/nextline-site
    - git fetch
    - git checkout develop
    - git reset --hard
    - git pull origin develop

after_staging:
  stage: deploy
  tags:
    - staging
  only:
    - develop
  script:
    - cd /applications/nextline/staging/nextline-site
    - rm -rf node_modules
    - npm i
    - ng build --configuration qa
    - sudo rm -rf /home/gitlab-runner/nextline/staging/dist
    - sudo mv dist /home/gitlab-runner/nextline/staging
    - cd /home/gitlab-runner/nextline/staging/dist/nextline-site
    - kill-port --port 7070
    - angular-http-server -p 7070 --silent


before_production:
  stage: prepare
  tags:
    - production
  only:
    - master
  script:
    - cd /applications/nextline/production/nextline-site
    - git fetch
    - git checkout master
    - git reset --hard
    - git pull origin master

after_production:
  stage: deploy
  tags:
    - production
  only:
    - master
  script:
    - cd /applications/nextline/production/nextline-site
    - rm -rf node_modules
    - npm i
    - ng build --prod
    - sudo rm -rf /home/gitlab-runner/nextline/production/dist
    - sudo mv dist /home/gitlab-runner/nextline/production
    - cd /home/gitlab-runner/nextline/production/dist/nextline-site
    - kill-port --port 8080
    - angular-http-server -p 8080 --silent
