stages:
  - prepare
  - master

before_staging:
  stage: prepare
  tags:
    - staging
  only:
    - master
  script:
    - cd /applications/nextline/staging/nextline-site
    - git fetch
    - git checkout master
    - git reset --hard
    - git pull origin master

after_staging:
  stage: deploy
  tags:
    - staging
  only:
    - master
  script:
    - cd /applications/nextline/staging/nextline-site
    - npm i
    - ng build --prod
    - sudo rm -rf /home/gitlab-runner/nextline/staging/dist
    - sudo mv dist /home/gitlab-runner/nextline/staging
    - cd /home/gitlab-runner/nextline/staging/dist/nextline-site
    - pm2 stop http-server -i index.html
    - pm2 start http-server -i index.html

