stages:
  - prepare
  - deploy

before_staging:
  stage: prepare
  tags:
    - staging
  only:
    - develop
  script:
    - cd /applications/nextline/staging/nextline-site
    - git fetch
    - git checkout develop
    - git reset --hard
    - git pull origin develop

after_staging:
  stage: deploy
  tags:
    - staging
  only:
    - develop
  script:
    - cd /applications/nextline/staging/nextline-site
    - npm i
    - ng build --prod
    - sudo rm -rf /home/gitlab-runner/nextline/staging/dist
    - sudo mv dist /home/gitlab-runner/nextline/staging
    - cd /home/gitlab-runner/nextline/staging/dist/nextline-site
    - pm2 restart http-server -i index.html
